CREATE TABLE "GCG_5703_COLORS"(
 "USER_ID" CHAR(8),
 "CCODE" CHAR(3),
 "PRODUCT_LINE" BIT,
 "PL_OPERATOR" CHAR(2),
 "PL_PL" CHAR(2),
 "GENERAL" BIT,
 "GEN_OPERATOR" CHAR(2),
 "GEN_LHS" LONGVARCHAR,
 "GEN_RHS" LONGVARCHAR,
 "COLOR" LONGVARCHAR,
 "TEXT_WHITE" BIT);